
export interface User{
    id: number
    name: string
}

export const userEmptyState: User = {
    id: 0,
    name : ''
}

// Generated by https://quicktype.io
export interface RickAndMortyUserError{
    error: string
}
export interface RickAndMortyUser {
    id:       number;
    name:     string;
    status:   string;
    species:  string;
    type:     string;
    gender:   string;
    origin:   Location;
    location: Location;
    image:    string;
    episode:  string[];
    url:      string;
    created:  string;
}

export interface Location {
    name: string;
    url:  string;
}
